/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app/usuarios'
import { Route as AuthenticatedAppMembrosRouteImport } from './routes/_authenticated/app/membros'
import { Route as AuthenticatedAppMapaRouteImport } from './routes/_authenticated/app/mapa'
import { Route as AuthenticatedAppMaoAmigaRouteImport } from './routes/_authenticated/app/mao-amiga'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app/financeiro'
import { Route as AuthenticatedAppEscalasRouteImport } from './routes/_authenticated/app/escalas'
import { Route as AuthenticatedAppEbdRouteImport } from './routes/_authenticated/app/ebd'
import { Route as AuthenticatedAppDepartamentosRouteImport } from './routes/_authenticated/app/departamentos'
import { Route as AuthenticatedAppCongregacoesRouteImport } from './routes/_authenticated/app/congregacoes'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app/configuracoes'
import { Route as AuthenticatedAppCalendarioRouteImport } from './routes/_authenticated/app/calendario'
import { Route as AuthenticatedAppAvisosRouteImport } from './routes/_authenticated/app/avisos'
import { Route as AuthenticatedAppAuditoriaRouteImport } from './routes/_authenticated/app/auditoria'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app/agenda'
import { Route as AuthenticatedAppFinanceiroIndexRouteImport } from './routes/_authenticated/app/financeiro.index'
import { Route as AuthenticatedAppFinanceiroRelatoriosRouteImport } from './routes/_authenticated/app/financeiro.relatorios'
import { Route as AuthenticatedAppFinanceiroLancamentosRouteImport } from './routes/_authenticated/app/financeiro.lancamentos'
import { Route as AuthenticatedAppFinanceiroDespesasRouteImport } from './routes/_authenticated/app/financeiro.despesas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/app/usuarios',
    path: '/app/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMembrosRoute = AuthenticatedAppMembrosRouteImport.update({
  id: '/app/membros',
  path: '/app/membros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMapaRoute = AuthenticatedAppMapaRouteImport.update({
  id: '/app/mapa',
  path: '/app/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMaoAmigaRoute =
  AuthenticatedAppMaoAmigaRouteImport.update({
    id: '/app/mao-amiga',
    path: '/app/mao-amiga',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/app/financeiro',
    path: '/app/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEscalasRoute = AuthenticatedAppEscalasRouteImport.update({
  id: '/app/escalas',
  path: '/app/escalas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppEbdRoute = AuthenticatedAppEbdRouteImport.update({
  id: '/app/ebd',
  path: '/app/ebd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDepartamentosRoute =
  AuthenticatedAppDepartamentosRouteImport.update({
    id: '/app/departamentos',
    path: '/app/departamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCongregacoesRoute =
  AuthenticatedAppCongregacoesRouteImport.update({
    id: '/app/congregacoes',
    path: '/app/congregacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/app/configuracoes',
    path: '/app/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCalendarioRoute =
  AuthenticatedAppCalendarioRouteImport.update({
    id: '/app/calendario',
    path: '/app/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAvisosRoute = AuthenticatedAppAvisosRouteImport.update({
  id: '/app/avisos',
  path: '/app/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditoriaRoute =
  AuthenticatedAppAuditoriaRouteImport.update({
    id: '/app/auditoria',
    path: '/app/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFinanceiroIndexRoute =
  AuthenticatedAppFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroRelatoriosRoute =
  AuthenticatedAppFinanceiroRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroLancamentosRoute =
  AuthenticatedAppFinanceiroLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)
const AuthenticatedAppFinanceiroDespesasRoute =
  AuthenticatedAppFinanceiroDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedAppFinanceiroRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/congregacoes': typeof AuthenticatedAppCongregacoesRoute
  '/app/departamentos': typeof AuthenticatedAppDepartamentosRoute
  '/app/ebd': typeof AuthenticatedAppEbdRoute
  '/app/escalas': typeof AuthenticatedAppEscalasRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRouteWithChildren
  '/app/mao-amiga': typeof AuthenticatedAppMaoAmigaRoute
  '/app/mapa': typeof AuthenticatedAppMapaRoute
  '/app/membros': typeof AuthenticatedAppMembrosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/despesas': typeof AuthenticatedAppFinanceiroDespesasRoute
  '/app/financeiro/lancamentos': typeof AuthenticatedAppFinanceiroLancamentosRoute
  '/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/congregacoes': typeof AuthenticatedAppCongregacoesRoute
  '/app/departamentos': typeof AuthenticatedAppDepartamentosRoute
  '/app/ebd': typeof AuthenticatedAppEbdRoute
  '/app/escalas': typeof AuthenticatedAppEscalasRoute
  '/app/mao-amiga': typeof AuthenticatedAppMaoAmigaRoute
  '/app/mapa': typeof AuthenticatedAppMapaRoute
  '/app/membros': typeof AuthenticatedAppMembrosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/financeiro/despesas': typeof AuthenticatedAppFinanceiroDespesasRoute
  '/app/financeiro/lancamentos': typeof AuthenticatedAppFinanceiroLancamentosRoute
  '/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/_authenticated/app/avisos': typeof AuthenticatedAppAvisosRoute
  '/_authenticated/app/calendario': typeof AuthenticatedAppCalendarioRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/congregacoes': typeof AuthenticatedAppCongregacoesRoute
  '/_authenticated/app/departamentos': typeof AuthenticatedAppDepartamentosRoute
  '/_authenticated/app/ebd': typeof AuthenticatedAppEbdRoute
  '/_authenticated/app/escalas': typeof AuthenticatedAppEscalasRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRouteWithChildren
  '/_authenticated/app/mao-amiga': typeof AuthenticatedAppMaoAmigaRoute
  '/_authenticated/app/mapa': typeof AuthenticatedAppMapaRoute
  '/_authenticated/app/membros': typeof AuthenticatedAppMembrosRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/financeiro/despesas': typeof AuthenticatedAppFinanceiroDespesasRoute
  '/_authenticated/app/financeiro/lancamentos': typeof AuthenticatedAppFinanceiroLancamentosRoute
  '/_authenticated/app/financeiro/relatorios': typeof AuthenticatedAppFinanceiroRelatoriosRoute
  '/_authenticated/app/financeiro/': typeof AuthenticatedAppFinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/agenda'
    | '/app/auditoria'
    | '/app/avisos'
    | '/app/calendario'
    | '/app/configuracoes'
    | '/app/congregacoes'
    | '/app/departamentos'
    | '/app/ebd'
    | '/app/escalas'
    | '/app/financeiro'
    | '/app/mao-amiga'
    | '/app/mapa'
    | '/app/membros'
    | '/app/usuarios'
    | '/app/'
    | '/app/financeiro/despesas'
    | '/app/financeiro/lancamentos'
    | '/app/financeiro/relatorios'
    | '/app/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/agenda'
    | '/app/auditoria'
    | '/app/avisos'
    | '/app/calendario'
    | '/app/configuracoes'
    | '/app/congregacoes'
    | '/app/departamentos'
    | '/app/ebd'
    | '/app/escalas'
    | '/app/mao-amiga'
    | '/app/mapa'
    | '/app/membros'
    | '/app/usuarios'
    | '/app'
    | '/app/financeiro/despesas'
    | '/app/financeiro/lancamentos'
    | '/app/financeiro/relatorios'
    | '/app/financeiro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/auditoria'
    | '/_authenticated/app/avisos'
    | '/_authenticated/app/calendario'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/congregacoes'
    | '/_authenticated/app/departamentos'
    | '/_authenticated/app/ebd'
    | '/_authenticated/app/escalas'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/mao-amiga'
    | '/_authenticated/app/mapa'
    | '/_authenticated/app/membros'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/'
    | '/_authenticated/app/financeiro/despesas'
    | '/_authenticated/app/financeiro/lancamentos'
    | '/_authenticated/app/financeiro/relatorios'
    | '/_authenticated/app/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/app/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/membros': {
      id: '/_authenticated/app/membros'
      path: '/app/membros'
      fullPath: '/app/membros'
      preLoaderRoute: typeof AuthenticatedAppMembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/mapa': {
      id: '/_authenticated/app/mapa'
      path: '/app/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AuthenticatedAppMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/mao-amiga': {
      id: '/_authenticated/app/mao-amiga'
      path: '/app/mao-amiga'
      fullPath: '/app/mao-amiga'
      preLoaderRoute: typeof AuthenticatedAppMaoAmigaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/app/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/escalas': {
      id: '/_authenticated/app/escalas'
      path: '/app/escalas'
      fullPath: '/app/escalas'
      preLoaderRoute: typeof AuthenticatedAppEscalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ebd': {
      id: '/_authenticated/app/ebd'
      path: '/app/ebd'
      fullPath: '/app/ebd'
      preLoaderRoute: typeof AuthenticatedAppEbdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/departamentos': {
      id: '/_authenticated/app/departamentos'
      path: '/app/departamentos'
      fullPath: '/app/departamentos'
      preLoaderRoute: typeof AuthenticatedAppDepartamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/congregacoes': {
      id: '/_authenticated/app/congregacoes'
      path: '/app/congregacoes'
      fullPath: '/app/congregacoes'
      preLoaderRoute: typeof AuthenticatedAppCongregacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/calendario': {
      id: '/_authenticated/app/calendario'
      path: '/app/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AuthenticatedAppCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/avisos': {
      id: '/_authenticated/app/avisos'
      path: '/app/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AuthenticatedAppAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/auditoria': {
      id: '/_authenticated/app/auditoria'
      path: '/app/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/financeiro/': {
      id: '/_authenticated/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/relatorios': {
      id: '/_authenticated/app/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/app/financeiro/relatorios'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/lancamentos': {
      id: '/_authenticated/app/financeiro/lancamentos'
      path: '/lancamentos'
      fullPath: '/app/financeiro/lancamentos'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroLancamentosRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
    '/_authenticated/app/financeiro/despesas': {
      id: '/_authenticated/app/financeiro/despesas'
      path: '/despesas'
      fullPath: '/app/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedAppFinanceiroRoute
    }
  }
}

interface AuthenticatedAppFinanceiroRouteChildren {
  AuthenticatedAppFinanceiroDespesasRoute: typeof AuthenticatedAppFinanceiroDespesasRoute
  AuthenticatedAppFinanceiroLancamentosRoute: typeof AuthenticatedAppFinanceiroLancamentosRoute
  AuthenticatedAppFinanceiroRelatoriosRoute: typeof AuthenticatedAppFinanceiroRelatoriosRoute
  AuthenticatedAppFinanceiroIndexRoute: typeof AuthenticatedAppFinanceiroIndexRoute
}

const AuthenticatedAppFinanceiroRouteChildren: AuthenticatedAppFinanceiroRouteChildren =
  {
    AuthenticatedAppFinanceiroDespesasRoute:
      AuthenticatedAppFinanceiroDespesasRoute,
    AuthenticatedAppFinanceiroLancamentosRoute:
      AuthenticatedAppFinanceiroLancamentosRoute,
    AuthenticatedAppFinanceiroRelatoriosRoute:
      AuthenticatedAppFinanceiroRelatoriosRoute,
    AuthenticatedAppFinanceiroIndexRoute: AuthenticatedAppFinanceiroIndexRoute,
  }

const AuthenticatedAppFinanceiroRouteWithChildren =
  AuthenticatedAppFinanceiroRoute._addFileChildren(
    AuthenticatedAppFinanceiroRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAuditoriaRoute: typeof AuthenticatedAppAuditoriaRoute
  AuthenticatedAppAvisosRoute: typeof AuthenticatedAppAvisosRoute
  AuthenticatedAppCalendarioRoute: typeof AuthenticatedAppCalendarioRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppCongregacoesRoute: typeof AuthenticatedAppCongregacoesRoute
  AuthenticatedAppDepartamentosRoute: typeof AuthenticatedAppDepartamentosRoute
  AuthenticatedAppEbdRoute: typeof AuthenticatedAppEbdRoute
  AuthenticatedAppEscalasRoute: typeof AuthenticatedAppEscalasRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRouteWithChildren
  AuthenticatedAppMaoAmigaRoute: typeof AuthenticatedAppMaoAmigaRoute
  AuthenticatedAppMapaRoute: typeof AuthenticatedAppMapaRoute
  AuthenticatedAppMembrosRoute: typeof AuthenticatedAppMembrosRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAuditoriaRoute: AuthenticatedAppAuditoriaRoute,
  AuthenticatedAppAvisosRoute: AuthenticatedAppAvisosRoute,
  AuthenticatedAppCalendarioRoute: AuthenticatedAppCalendarioRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppCongregacoesRoute: AuthenticatedAppCongregacoesRoute,
  AuthenticatedAppDepartamentosRoute: AuthenticatedAppDepartamentosRoute,
  AuthenticatedAppEbdRoute: AuthenticatedAppEbdRoute,
  AuthenticatedAppEscalasRoute: AuthenticatedAppEscalasRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRouteWithChildren,
  AuthenticatedAppMaoAmigaRoute: AuthenticatedAppMaoAmigaRoute,
  AuthenticatedAppMapaRoute: AuthenticatedAppMapaRoute,
  AuthenticatedAppMembrosRoute: AuthenticatedAppMembrosRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
